name: 🚀 Build and deploy by ftp

on:
  push:
    - master
    - main

jobs:

  ftp-build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: https://github.comactions/checkout@v3

    - uses: https://github.comactions/setup-node@v3
      with:
        node-version: 18

    - run: npm i --location=global pnpm@7
    - run: pnpm i
    - run: pnpm build
    - run: npm run export

    - name: 📂 Sync files
      uses: https://github.comSamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}